extends Node

enum TileType {IRON, SILVER, SILICON, GOLD, BELT, LBELT, TBELT, FURNACE, CUTTER, FACTORY, ASSEMBLY, RESELLER}

enum Power {LOWEST, LOW, MEDIUM, HIGH, HIGHEST}

enum ObjectType {IRON_ORE, SILVER_ORE, SILICON_ORE, GOLD_ORE, \
				 IRON_PLATE, SILVER_PLATE, SILICON_PLATE, GOLD_PLATE, \
				 IRON_WIRE, SILVER_WIRE, SILICON_WIRE, GOLD_WIRE }
